spring.application.name=Ex_029_ControllerAdviceGlobalExceptionHandler
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/springrestdb
spring.datasource.username=root
spring.datasource.password=Varun$NewMac

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true